### ISSUE TITLE
Data Collection 

### ISSUE THREAD

**Issue by lenasong** [huntallcott/PhoneAddiction#4] opened 2018-08-09 02:42 UTC
https://docs.google.com/document/d/18vOEnNFHWe3X0srM4KOSBff9nrUhzOL5X2Cxj58UJas/edit?usp=sharing

**Comment by lenasong** [comment] 2018-08-09 03:10
I've started jotting down some of the functions we are looking for in the Google doc above. @KellyBuckley, would be great if we can consult someone at Microsoft and actually test things out. 
@gentzkow @huntallcott let us know if you have any other good developer candidates in mind for programming this.

**Comment by lenasong** [comment] 2018-08-13 15:11
@KellyBuckley @gentzkow @huntallcott I had a quick call with a developer at Google about what we are looking for and its technical feasibility with meeting notes added [here](https://docs.google.com/document/d/18vOEnNFHWe3X0srM4KOSBff9nrUhzOL5X2Cxj58UJas/edit?usp=sharing).

**Key takeaways:**
-Precise and frequent GPS tracking is difficult and battery-draining, but tracking subjects at a few locations can be done easily via geofencing, i.e. if we only care about whether they are in a fixed set of locations (e.g. school, home, movie theatre)
-Not possible to write an app that has direct access to data on system app such as Dash Board unless the phone is in debugging mode. Possible ways to export data still are 1) user takes a photo of Dash Board/Screen Time summary 2) user connect phone to desktop and run desktop application/script

**Comment by huntallcott** [comment] 2018-08-14 02:06
Great thanks @lenasong .
1. I'm souring on the GPS. My guess is that a big part of the location substitution, if any, would be going to friends' dorm rooms. If we don't have precise locations, we won't see that. Minor question though: do you know if we can get geofence data when people *leave* their home, not just when they arrive? Seems like our only hope would be to keep track of total time at home, if we can measure when people *leave* as well as approach home.

2. How long does the dashboard/screen time system app keep a history? Could we have people plug into an app once per month, or does it need to be more frequent? I lean towards that instead of taking a photo, if possible, because I think it will be more reliable and will give us more data than can be seen on one photo.

3. Seems like trust will be important if we go in the direction of a script. We would either need a really official looking website or to have people physically come into a lab.

**Comment by KellyBuckley** [comment] 2018-08-14 11:46
I talked with someone at Microsoft who said there are interns using test phones but they will be available 8/24 (when the interns leave). I haven't found anyone yet who does mobile development.

**Comment by lenasong** [comment] 2018-08-14 15:40
some quick replies for questions from @huntallcott:
1. with geofencing we can get both entering and leaving fixed locations
2. for dashboard on android, what I've heard is that the system app keeps the entire history since the start of using the app. Will have to check for ios when we find a developer to write a script and test things out
3. agreed

**Comment by KellyBuckley** [comment] 2018-08-15 14:31
I emailed with a developer from Microsoft who said:
"On iOS, I looked quickly at the documentation and did not see any mention of a public API for reading screen time information. I have found that Apple only exposes user data to an app when it’s absolutely necessary,  I am not surprised by the lack of API."

When I asked where the documentation he referenced was he said:
"I didn’t find any documentation 😊.  https://developer.apple.com/ is where all the iOS documentation lives.  I looked around for ScreenTime and “Screen Time”.  If there was a kit for the app, I’d expect to see it in the help."

So it looks like for iOS there isn't a way to programatically access the data.

**Comment by lenasong** [comment] 2018-08-21 16:32
@KellyBuckley what kind of test phones does microsoft have? 

The digital wellbeing app is now available for testing on pixel devices  - https://www.android.com/versions/pie-9-0/digital-wellbeing-beta/

Any luck finding a developer at Microsoft for either ios or android? We don't necessarily need someone with app development experience - they just need to know how to access and retrieve data from apps and code a desktop script. If not, we should also start looking into Upwork.

**Comment by KellyBuckley** [comment] 2018-08-21 17:40
@lenasong the phones are just normal phones that aren't hooked up to a data/phone plan. I will be able to see what's available Monday after the interns leave. 

I realized I wasn't clear earlier about the developer -- I was looking for a mobile dev to ask advice from, not to build an app (we can't ask anyone at Microsoft to build an app since they have to work on whatever their team does, except for RAs but none of us have that skill set). I pasted the comments from the developer I emailed with above. Basically he said there is no way for an app to access the iOS Screen Time data, we'd have to use screenshots or something like that.

**Comment by lenasong** [comment] 2018-08-21 20:52
@KellyBuckley thanks for checking. I agree with the developer's note on iOS - exporting could work only if Apple releases the public API for Screen Time later, but we can't count on it. 

Is it possible to arrange a conversation with the digital well-being team at Apple? @huntallcott @gentzkow 
Things would be much easier if Apple can help us with either of these:
1) add an exporting function to their Screen Time app directly  
2) give us the access to the private API for Screen Time 

Otherwise screenshot might be our way to go.

PS - Here's a recent [article ](https://www.wired.co.uk/article/digital-wellbeing-android-ios-facebook-instagram) on what psychologists think of these apps.

**Comment by gentzkow** [comment] 2018-08-21 20:58
Hi @lenasong,

We've talked to the teams at both Apple and Google. Both were very clear that there are no plans to expose the content of the apps in a way that other apps can access. I think we would have to work with screenshots.

**Comment by lenasong** [comment] 2018-08-27 17:17
I double checked with developers at Google. It's true we cannot use APIs and access the system app directly. They suggested a workaround (that's available on Android, need to double check for iOS): https://developer.android.com/studio/debug/device-file-explorer. 

@KellyBuckley can you help look into this with the test phones?

**Comment by KellyBuckley** [comment] 2018-08-27 18:42
@lenasong I've emailed the contact I have here about getting the phones, but haven't heard back yet. Will let you know when I do.

**Comment by huntallcott** [comment] 2018-08-28 02:12
@lenasong @KellyBuckley thanks for this work.
It seems clear to me that we need to bring on a developer that can work with us to develop screenshot capability and/or advise/develop tools for using the system apps for export if possible. I have emailed Shehnaz at Stanford and cc'd Matt and Lena.

**Comment by lenasong** [comment] 2018-08-28 17:07
@huntallcott @KellyBuckley @gentzkow 
I've spoken to a couple more android and iOS developers and their impression is that we'll need a team of developers to make something robust under our time constraints. The export option available on android is unlikely to be available on iOS.  

Are we thinking about developing our own version of the Moment app then?

One additional question is how do we show credibility in our online recruitment. I'm usually hesitant to install and keep any third-party apps on my phone. Are we pitching our app to be a data collection tool just for our experiment, or an app that actually has value to students as a commitment app ("here's an app that helps manage your smartphone usage and you can make money in the process!")?

**Comment by KellyBuckley** [comment] 2018-08-28 18:13
@lenasong I agree with the developers that building a new Moment app would be super hard. I was thinking we'd want something at the level of an app that sends you reminders to take screen shots of Moment or the built in apps and maybe even collects those screen shots and bulk sends them to us. (Although I'm not sure who inputs the data from thousands of screen shots.)

**Comment by huntallcott** [comment] 2018-08-28 18:54
Agree with Kelly; I don't think we need a full app. We just need the ability to export data and/or take a screenshot. Let's start with one developer for now?

**Comment by gentzkow** [comment] 2018-08-29 08:41
Definitely. I continue to think we're likely to end up with wanting to do screenshots. I'm not sure we need an app at all. As @lenasong says, getting people to install our app would be an additional hurdle and I think we could do reminders pretty well via text messages.

We should remember that there are still issues to think through with screenshots:
* Can people game by editing the screenshot directly to change the numbers?
* Can people game by taking the screenshot at the wrong time (e.g., send in a screenshot from the beginning of the week and claim it's the screenshot from the end of the week)?
* What time periods / sets of apps are shown on a single screen; how many screenshots will people need to send us so we have all relevant info, and how are we going to stitch these together into usable data?

**Comment by lenasong** [comment] 2018-08-29 17:54
Great. The answers to these should be clearer once we play around with the beta versions of the apps on test phones - one of the developers I talked to mentioned that running OCR on these screenshots shouldn't be too difficult. I'll get started on looking for mobile developers on Upwork. 

@huntallcott @gentzkow Do you already have an account there that we can use? If not I'm going to post the job with a new account. 

@KellyBuckley I'll probably need help defining the technical details of the project.

**Comment by huntallcott** [comment] 2018-08-29 18:07
I'd just use a new account. Thanks.

**Comment by KellyBuckley** [comment] 2018-08-29 18:12
@lenasong feel free to send me a draft or let me know if you have questions

**Comment by lenasong** [comment] 2018-08-31 15:10
I've drafted a job posting on upwork, with the content in pdf [here](https://drive.google.com/file/d/1T8fCgQ3JrquNm2LCYpnxHbOnt1e1p_uT/view?usp=sharing).

Couple of questions and comments:
- Total compensation is set at 5k for the entire project for now. Let me know if you think another rate is more appropriate
- I'm leaving GPS tracking such as geofencing out since that would require us building a third-party app 

@KellyBuckley take a look and let me know if we have the technical details correct? Have emailed you the password separately so you can edit directly.

**Comment by KellyBuckley** [comment] 2018-08-31 19:05
@lenasong just updated the description on the Upwork website. I took out the part about the server since I don't actually think we'll be building our own (I would guess storage will still be on something like dropbox and processing will happen on their computer or we would get a VM).

Here's the description now (I didn't change other things in the pdf):

We are a team of researchers at New York University and Stanford University working on understanding smartphone addiction in college students. We are looking for a developer to retrieve data from digital well-being apps that Apple and Google are introducing on iOS12 (called "Screen Time") and Android Pie (called "Digital Wellbeing"), on the phones of our study participants. For example, these apps will track how much time someone spends on different apps on their phone and we are interested in getting this data.

Deliverable: 
-Overall: retrieve smartphone usage data from system apps on both Android and iOS over the course of one academic year, send raw data to us, and transform data into a format that is easily analyzable by statistical software 
-Immediate: understand feasibility of automatically transferring data to us from beta versions of digital well-being apps 
-Next two months: work with researchers to define approach for data extraction. This could entail possibly building a mobile or desktop program to extract the data from the digital well-being apps or, if this isn't possible through APIs, creating a program to extract the data from screen shots.
-After initial set-up: regular maintenance and troubleshooting 

We are looking for a creative freelancer familiar with mobile development and possibly image processing. 

Join this unique opportunity to be involved in an interesting research project that will make an impact.

**Comment by huntallcott** [comment] 2018-09-03 00:10
All looks great. One question -- we're paying by the hour, yes? Not $5k flat? It seems like we don't know much about the total number of hours yet. Just checking on your thinking. Many thanks.

**Comment by huntallcott** [comment] 2018-09-03 22:15
Just talked with @gentzkow. He wants to emphasize that his conversations have been pretty clear that it will be difficult to extract the data via any computerized way other than screenshots. Furthermore, we can process the screenshots ourselves without tech help from Upwork.
The upshot is that we should not hire somebody from Upwork.
I am sorry that I didn't process this info earlier. 

What we do want to know is what the screenshot process will look like. What is the time frame of the data that we can screenshot (day/week/month?), what info is included, how many screen shots would be required, etc, for each of iOS and Android-P. @KellyBuckley can you push harder on the test phones using your excellent powers of persuasion and organizational red-tape-cutting?

**Comment by KellyBuckley** [comment] 2018-09-04 01:14
@huntallcott I heard back from the guy in the Garage who has the phones and he has one Android phone we can borrow but no iPhones. I am working from Redmond until Wednesday and will be back in the office Thursday to check it out and see if it's possible to get the software on it. Do you think it would be worth purchasing an iPhone from somewhere? Or do any of you know someone who has an old one laying around?

**Comment by KellyBuckley** [comment] 2018-09-06 19:16
@huntallcott @gentzkow Lena confirmed that the Android phone I borrowed from Microsoft will not run the new OS (she has the same phone). Like I said in the meeting, when the official (i.e. non-beta) OS is released for Apple I can download it on my phone.

**Comment by huntallcott** [comment] 2018-09-06 21:29
@KellyBuckley thanks for looking at that.
Incidentally - I think @gentzkow's sleuthing during the meeting suggested that with the new iOS features, we would take weekly screenshots, and probably no possibility of monthly. If we are planning to do weekly screenshots of app-specific usage, iOS of course already has that ability. So it seems like we can be essentially full steam ahead now.

**Comment by huntallcott** [comment] 2018-09-15 14:02
@lenasong ,
I hope you're well. Would you be willing to *very quickly* accelerate the testing of this particular ability to upload screenshots of iOS time usage from the past week on the battery screen?
It seems like the next step for our project. I also have a highly time-sensitive reason for this capability on another project.

So what I'd propose is to:
1. Develop a very short qualtrics survey that promises a $2 gift card and asks:
i. in what year were you born?
ii. On an average day in the past 4 weeks, how many minutes would you say you spent on Facebook, including through the Facebook app on your phone?
iii. Do you have an iPhone? (If no, then out)
iv. Then asks for people to upload screenshots from their battery screen.
v. Collect info for payment.
In the survey, please keep track of how long it takes people to complete each question, if possible.

These data won't be used for research and are not identifiable, so we don't need IRB.

2. Send a web link to this survey to us for review.

3. Recruit enough people from Facebook to get say 100 people to start. (I can connect you with Raj at MSR who can give more info on how to do the recruiting and payments.) Then let's see how many people complete, and how long it takes them. 

Is this something you could complete by mid-next week? Call me if questions?

**Comment by lenasong** [comment] 2018-09-15 14:27
@huntallcott no problem - I can draft the Qualtrics survey this weekend. It would be great if you can connect me with Raj. 

iOS 12 is available on Monday and is compatible with almost all devices. Should we try Screen Time or stick with the battery screen?

**Comment by huntallcott** [comment] 2018-09-15 14:36
Re: screen time vs. battery, I think we want to balance:
1. How good is the functionality
2. How many people will have iOS 12? For our eventual pilot and for this other project, I imagine wanting to get actual data in say 10 days. And especially for this pre-survey you're doing early next week I'm not sure how many people will have iOS 12, and presumably nobody will have historical data.

**Comment by huntallcott** [comment] 2018-09-15 14:36
And thank you @lenasong for accelerating this!

**Comment by lenasong** [comment] 2018-09-16 22:10
Here's a [preview ](https://nyu.ca1.qualtrics.com/jfe/preview/SV_1zPT2HUFISdmxq5?Q_SurveyVersionID=current&Q_CHL=preview) to the survey.

Note that the screenshot upload question asks for last 7 days (instead of last 24 hours) and payment specifies that we will send a follow-up email with e-gift card. 

Let me know how it looks.

**Comment by huntallcott** [comment] 2018-09-17 00:58
Thanks Lena!
This looks like a good start. 

A couple of thoughts:
1. I'd change the first question to: "This study will take approximately 3-5 minutes to complete. We’ll ask you a couple of basic questions and then guide you through the process to upload a screen shot from your phone. We'll give you a $2 gift card when you finish. Are you willing to participate?" The reason is that I think this will more closely approximate attrition in the actual survey, where people may be aware that we are going to ask for screenshots.
2. In general, I think we need to be much clearer about the upload process to make this possible for the average adult. As an example, the instructions could read:
1.	Click on the Settings app on your iPhone
2.	Within the settings app, scroll down and click on the Battery icon

instead of just "Settings -> Battery"

3. Can you make sure these instructions work for all iPhones? I have an iPhone SE, and the screenshot is top button (not side button) plus Home. 
4. I think we need crystal clear instructions on how to upload after you take the pics.
a. "If you are taking the survey on your PC, plug your iPhone into your PC and ... OR email the screenshot to yourself by following xyz steps."
b. "If you are taking the survey on your iPhone, ..." (how the heck do you drag and drop on an iPhone?

Can you revise per these ideas? Many thanks.

**Comment by lenasong** [comment] 2018-09-17 16:44
Here's the [survey ](https://nyu.ca1.qualtrics.com/jfe/preview/SV_1zPT2HUFISdmxq5?Q_SurveyVersionID=current&Q_CHL=preview)with revised instructions. Also added a quota for 120 responses who meets validation questions (willing to take survey and has an iPhone). Including a few extra in case screenshots are not captured properly. 

I've changed the wording for timing of payment to immediately after completion of survey by email. 

How do we want to set up payment on this short survey? I talked to Raj and Luca - Luca mentioned that he can help set up immediate payment (email from Rewards Genius) from the FB project account.

**Comment by huntallcott** [comment] 2018-09-17 18:04
@lenasong! This looks great. 
In the snap below, I see a weird font in the first paragraph and a missing word in 7, i.e. I think it should say "Upload screenshots to the survey."
Other than that I'm pretty happy with this. 

One other thing to consider: is there a way to gather info on how/why people are failing? e.g. somewhere on the upload screen, perhaps on the bottom, we have another optional box saying "If you're having trouble with this upload, please help us to help future participants! Please write here any additional instructions that would have been helpful."

![image](https://user-images.githubusercontent.com/23505296/45640909-ec220480-ba81-11e8-83f3-1178cdbbd69e.png)

Other than that I'm good with this. Unless @gentzkow or @KellyBuckley has something to add, I would say to go ahead and launch, with the goal of getting 100 people to begin the survey. Then collect stats on attrition after each question, how many valid uploads we get (which will involve looking at each one), and the text of any comments that we get per above. Then post that in a pdf here?

Many thanks for making this happen quick!

**Comment by lenasong** [comment] 2018-09-17 19:38
@huntallcott thanks for the feedback. I've made the proposed changes and will test out data collection for incomplete surveys. The fastest option for a partial answer to be available is 4 hours after the start of the survey - I've submitted a couple and will let you know how well this works.

**Comment by lenasong** [comment] 2018-09-18 19:09
Finalizing payment details with Luca now and will send out the survey soon. 

To avoid payment to invalid responses, we are going to promise participants payments at end of the study in a week, instead of immediate, automatic payment.

@KellyBuckley can you help with validating uploads as they come in? I'll provide more details over email.

**Comment by KellyBuckley** [comment] 2018-09-18 19:31
@lenasong I can help some, but I am a little short on time trying to finish stuff to get the facebook project off the ground next week, so if it's a lot let me know and we can maybe pull in Raj

**Comment by huntallcott** [comment] 2018-09-20 11:31
@lenasong ,
Thanks for your great efforts in making this happen.
Is there a way you could provide results by later today?
Matt and I have a meeting tomorrow morning and would really benefit from being able to digest the results before-hand.
Thanks again.

**Comment by lenasong** [comment] 2018-09-20 11:40
@huntallcott When do you need the results by? Raj and Kelly are helping out looking at the screenshots this afternoon and I should be able to provide an analysis summary by early evening our time.

**Comment by huntallcott** [comment] 2018-09-20 12:02
Early evening would be fine. Thanks to all of you.

**Comment by lenasong** [comment] 2018-09-21 00:21
See attached for a summary from our short survey [here](https://drive.google.com/file/d/1uTw2Nx-IzNCxSZ5YrrZW0fJGCtn5Vi9g/view?usp=sharing).

Let me know if you have any comments/questions.

**Comment by huntallcott** [comment] 2018-09-21 02:03
@lenasong , this is tremendous, thanks for pulling this off. 
Just so I'm totally clear, what is the bottom line? It looks like there were 179 people who had iPhones and finished the daily minutes question. Then of those 179, 122 uploaded something. Of those, 44 did it perfectly, and maybe some share of the rest could do it perfectly with practice and/or coaching and/or perfect instructions.
Does that sound like a fair characterization? 
Thanks again.

**Comment by lenasong** [comment] 2018-09-21 02:32
@huntallcott yes exactly. In fact, out of those who uploaded something incorrectly, more than half of them missed the instruction to click to show hours. From the few screenshots I see of Screen Time, that doesn't seem to be a relevant issue on iOS 12.

**Closed** 2019-01-27 17:41 UTC
